parameters:
    develoid_translator_google_translator_class: Develoid\TranslatorBundle\Google\Translator
    develoid_translator_yandex_translator_class: Develoid\TranslatorBundle\Yandex\Translator
    develoid_translator_microsoft_translator_class: Develoid\TranslatorBundle\Microsoft\Translator

services:
    develoid_translator.default_translator:
        class: Develoid\TranslatorBundle\Translator
        arguments: [ @service_container, %develoid_translator.default% ]